name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'
  push:
      tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:

  pico_elevator:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    steps:
      - uses: actions/checkout@v4
        with:
          path: micro_ros_raspberrypi_pico_sdk

      - name: Dependencies
        shell: bash
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -y g++ gcc-arm-none-eabi doxygen libnewlib-arm-none-eabi git python3 cmake
          git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk

      - name: Build
        shell: bash
        run: |
          export PICO_SDK_PATH=$HOME/pico-sdk
          cd micro_ros_raspberrypi_pico_sdk
          mkdir build
          cd build
          cmake ..
          make
          (test -f pico_elevator.uf2) && true || false

      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y %H:%M')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Update  ${{ steps.date.outputs.date }}
          body_path: pico_elevator.uf2
          draft: false
          prerelease: false