name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'
  pull_request:
    branches:
      - '**'

jobs:

  pico_elevator:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    steps:
      - uses: actions/checkout@v4
        with:
          path: micro_ros_raspberrypi_pico_sdk

      - name: Dependencies
        shell: bash
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -y g++ gcc-arm-none-eabi doxygen libnewlib-arm-none-eabi git python3 cmake
          git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk

      - name: Build
        shell: bash
        run: |
          export PICO_SDK_PATH=$HOME/pico-sdk
          cd micro_ros_raspberrypi_pico_sdk
          mkdir build
          cd build
          cmake ..
          make
          (test -f pico_elevator.uf2) && true || false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: micro-ROS program auto-update ${{ steps.date.outputs.date }}
          title: micro-ROS program auto-update ${{ steps.date.outputs.date }}
          body: This PR is autogenerated and updates the program pico_elevator. Close and reopen to trigger CI.
          branch: autoupdate_micro_ros_rpipico_${{ matrix.branch }}
          delete-branch: true
          base: ${{ matrix.branch }}
          token: ${{ secrets.PR_TOKEN }}